import json
import re
from typing import Dict, List, Optional
from urllib.parse import urlparse

from utils import (
    vt_lookup,
    vt_url_lookup,
    vt_domain_lookup,
    whois_lookup,
    dns_lookup,
    parse_html,
    detect_homograph,
    is_ip_address,
    URL_SHORTENERS,
    SUSPICIOUS_TLDS,
    BRAND_KEYWORDS,
)
import tldextract

def analyze_file_type(
    file_json: dict,
    depth: int,
    extension: str,
    parent_extension: str = None
) -> dict:

    # Canonical definitions
    CANONICAL_TYPES = {
        "office_doc": {
            "doc", "docx", "docm",
            "xls", "xlsx", "xlsm",
            "ppt", "pptx", "office_doc"
        },
        "pdf": {"pdf"},
        "archive": {"zip", "rar", "7z", "tar", "gz", "archive"},
        "executable": {"executable", "exe", "dll", "elf", "macho"},
        "script": {"script", "js", "vbs", "ps1", "bat", "sh"},
        "image": {"image", "png", "jpg", "jpeg", "gif", "bmp", "heic"},
        "text": {"image", "txt", "csv"}
    }

    EXTENSION_TO_TYPE = {
        ext: category
        for category, exts in CANONICAL_TYPES.items()
        for ext in exts
    }

    EXPECTED_CHILDREN = {
        "office_doc": {"xml", "image", "rels", "ole", "png", "jpg", "jpeg", "gif", "bmp", "heic"},
        "pdf": {"image", "font", "text", "png", "jpg", "jpeg", "gif", "bmp", "heic", "txt", "csv"},
        "archive": {"office_doc", "pdf", "image", "text", "png", "jpg", "jpeg", "gif", "bmp", "heic", "txt", "csv"},
        "image": set()
    }


    extension = extension.lower() if extension else None
    file_type = EXTENSION_TO_TYPE.get(extension, "unknown")

    mime = file_json.get("mime", [])
    yara = file_json.get("yara", [])

    # Root file logic
    if depth == 0:
        classification = "Unusual"

        if (
            any(file_type in m for m in mime) or
            any(file_type in y for y in yara) or
            any(extension in m for m in mime) or
            any(extension in y for y in yara)
        ):
            classification = "Normal"

        return mime, classification
        

    # Child file logic
    classification = "Unusual"
    parent_extension = EXTENSION_TO_TYPE.get(parent_extension,"unknown")
    expected = EXPECTED_CHILDREN.get(parent_extension, set())

    for m in mime:
       for e in expected:
          if e in m:
             classification = "Normal"

    for m in yara:
       for e in expected:
          if e in m:
             classification = "Normal"

    if extension in expected or file_type in expected:
        classification = "Normal"

    return mime, classification
    



def get_extension(filename: str) -> Optional[str]:
    if "." not in filename:
        return None
    return filename.rsplit(".", 1)[-1].lower()


def analyze_iocs(iocs: list) -> tuple[int, list[str]]:
    score = 0
    reasons = []

    suspicious_tlds = {
    ".tk", ".ml", ".ga", ".cf", ".gq",
    ".xyz", ".buzz", ".top", ".loan", ".bond",
    ".faith", ".stream", ".download", ".online",
    ".tech", ".work", ".country", ".kim",
    ".science", ".ninja", ".date", ".racing",
    ".cricket", ".win", ".space", ".accountant",
    ".realtor", ".christmas", ".gdn", ".men", ".pro", ".click", ".site"
    }

    for item in iocs:
        ioc = item.get("ioc", "")
        ioc_type = item.get("ioc_type", "")

        if ioc_type in {"url", "domain"}:
            score += 5
            for tld in suspicious_tlds:
                if tld in ioc:
                    score += 20
                    reasons.append(f"Suspicious TLD detected: {tld}")

        if ioc_type == "ip":
           score += 30
           reasons.append("IP exist in the file")

    vt_result = vt_lookup(ioc, ioc_type)

    if vt_result:
        if vt_result["malicious"] > 0:
            score += 100
            reasons.append(
                f"VirusTotal malicious IOC: {ioc} "
                f"(detections: {vt_result['malicious']})"
            )
        elif vt_result["suspicious"] > 1:
            score += 50
            reasons.append(
                f"VirusTotal suspicious IOC: {ioc}"
            )

    return score, reasons

def check_automated_files(creator):
   
    HIGH_RISK_CREATORS = {
        "headless", "puppeteer", "playwright", "selenium", "chromium"
    }

    PDF_ENGINES = {
        "skia", "pdfium", "wkhtmltopdf", "weasyprint",
        "prince", "pdfkit", "reportlab"
    }

    SCRIPT_TOOLS = {
        "libreoffice", "openoffice", "unoconv",
        "pandoc", "ghostscript"
    }
    score = 0
    creator = creator.lower()
    reasons = []
    if any(k in creator for k in HIGH_RISK_CREATORS):
        score += 40
        reasons.append(f"Document generated by automated browser: {creator}")

    elif any(k in creator for k in PDF_ENGINES):
        score += 30
        reasons.append(f"Programmatic PDF generator detected: {creator}")

    elif any(k in creator for k in SCRIPT_TOOLS):
        score += 20
        reasons.append(f"Document generated via scripting tool: {creator}")

    return score , reasons

def check_yara(yara_out):
   matches = yara_out.get("matches", [])
   score = 0
   reasons = []
   if matches:
    for rule in matches:
        score += 30
        reasons.append(f"yara rule fired: {rule}")

   return score , reasons

def compute_score(strelka_json,file_path):
  
  score = 0
  reasons = []
  verdict = "Benign"
  extension = get_extension(file_path)
  for jsn in strelka_json:
    depth = jsn.get("file", {}).get("depth")
    if depth == 0:
      file_type,classification = analyze_file_type(jsn.get("file", {}).get("flavors", {}),depth,extension)
      if classification == "Unusual" :
         score = score + 50
         reasons.append(f"Umatched file type, original: {extension}, detected: {file_type}")
    else:
      file_type,classification = analyze_file_type(jsn.get("file", {}).get("flavors", {}),depth,extension,extension)
      if classification == "Unusual" :
         score = score + 50
         reasons.append(f"Umatched file type included, parent: {extension}, detected: {file_type}")
    
    mime = jsn.get("file", {}).get("flavors", {}).get("mime", [])
    yara = jsn.get("file", {}).get("flavors", {}).get("yara", [])
    
    for m in mime:
      if "encrypted" in m:
        score += 50
        reasons.append("Encrypted file")
    for m in yara:
      if "encrypted" in m:
        score += 50 
        reasons.append("Encrypted file")

    clamav_scan = jsn.get("scan", {}).get("clamav", {})

    infected_raw = clamav_scan.get("Infected files", "0")

    try:
        infected = int(infected_raw)
    except (ValueError, TypeError):
        infected = 0

    if infected > 0:
        score += 100
        reasons.append("ClamAV detected malware signature")

    entropy = jsn.get("scan", {}).get("entropy",{}).get("entropy")

    if entropy > 7.2:
       score += 25
       if entropy > 7.8:
          score += 10
       reasons.append(f"High entropy = {entropy}")

    if jsn.get("iocs",[]):
       s , r = analyze_iocs(jsn.get("iocs",[]))
       score += s
       for u in r:
          if u not in reasons:
            reasons.append(u)

    if jsn.get("scan",{}).get("exiftool",{}).get("creator"):
       s, r = check_automated_files(jsn.get("scan",{}).get("exiftool",{}).get("creator"))
       score += s
       for u in r:
          reasons.append(u)

    if jsn.get("scan",{}).get("exiftool",{}).get("producer"):
       s, r = check_automated_files(jsn.get("scan",{}).get("exiftool",{}).get("producer"))
       score += s
       for u in r:
          reasons.append(u)

    if jsn.get("scan",{}).get("yara",{}):
       s, r = check_yara(jsn.get("scan",{}).get("yara",{}))
       score += s
       if r:
        for u in r:
            reasons.append(u)
    
    if jsn.get("pdf",{}).get("yara",{}):
       s, r = check_yara(jsn.get("pdf",{}).get("yara",{}))
       score += s
       if r:
        for u in r:
            reasons.append(u)
    

  if score >= 50 :
    verdict = "Malicious"

  
  return score, verdict, reasons


# URL Analysis – Scoring Functions

def analyze_url_structure(url: str) -> tuple[int, list[str]]:
    """
    Analyse the raw URL string for structural red-flags.

    Checks performed:
      • Excessive length (>100 chars)
      • Suspicious characters (@ sign, % encoding, multiple dots)
      • IP address used instead of domain name
      • Known URL shortener domains
      • Suspicious TLDs (.tk, .xyz, …)
      • Homograph / look-alike domains imitating popular brands
    """
    score = 0
    reasons: list[str] = []

    parsed = urlparse(url)
    hostname = (parsed.hostname or "").lower()
    extracted = tldextract.extract(url)
    tld = extracted.suffix.split(".")[-1].lower() if extracted.suffix else ""

    if len(url) > 200:
        score += 15
        reasons.append(f"Very long URL ({len(url)} chars)")
    elif len(url) > 100:
        score += 5
        reasons.append(f"Long URL ({len(url)} chars)")

    if "@" in url:
        score += 10
        reasons.append("URL contains '@' – possible credential-based redirect")

    pct_count = url.count("%")
    if pct_count > 4:
        score += 15
        reasons.append(f"Excessive percent-encoding ({pct_count} occurrences)")

    dot_count = hostname.count(".")
    if dot_count >= 4:
        score += 10
        reasons.append(f"Excessive subdomains in hostname ({dot_count} dots)")

    if is_ip_address(hostname):
        score += 30
        reasons.append(f"URL uses raw IP address: {hostname}")

    full_domain = f"{extracted.domain}.{extracted.suffix}".lower()
    if full_domain in URL_SHORTENERS:
        score += 15
        reasons.append(f"URL shortener detected: {full_domain}")

    if tld in SUSPICIOUS_TLDS:
        score += 20
        reasons.append(f"Suspicious TLD: .{tld}")

    brand = detect_homograph(hostname)
    if brand:
        score += 40
        reasons.append(f"Possible homograph / look-alike of '{brand}'")

    if parsed.scheme != "https":
        score += 10
        reasons.append("URL does not use HTTPS")

    return score, reasons


def analyze_domain_intelligence(domain: str) -> tuple[int, list[str]]:
    """
    Use WHOIS and DNS data to assess domain trustworthiness.

    Risk rules:
      • Domain age < 30 days → +30
      • Domain age < 90 days → +15
      • Hidden WHOIS / privacy guard → +10
      • No DNS records at all → +20
    """
    score = 0
    reasons: list[str] = []

    # --- WHOIS ---
    whois_data = whois_lookup(domain)

    if whois_data.get("error"):
        score += 10
        reasons.append(f"WHOIS lookup failed: {whois_data['error']}")
    else:
        age = whois_data.get("domain_age_days")
        if age is not None:
            if age < 30:
                score += 30
                reasons.append(f"Very new domain (registered {age} days ago)")
            elif age < 90:
                score += 15
                reasons.append(f"Recently registered domain ({age} days ago)")

        if whois_data.get("whois_hidden"):
            score += 10
            reasons.append("WHOIS information is hidden / privacy-protected")

        registrar = whois_data.get("registrar")
        if registrar:
            reasons.append(f"Registrar: {registrar}")

    # --- DNS ---
    dns_data = dns_lookup(domain)
    if dns_data.get("error"):
        score += 20
        reasons.append("No DNS records found for domain")

    return score, reasons


def analyze_page_content(html: str, redirect_count: int) -> tuple[int, list[str]]:
    """
    Analyse fetched HTML content for phishing / malicious signals.

    Checks:
      • Hidden iframes
      • External suspicious scripts
      • Obfuscated JavaScript (eval, atob, unescape …)
      • Login forms (phishing indicator)
      • Suspicious urgency keywords
      • Excessive redirects (≥3)
    """
    score = 0
    reasons: list[str] = []

    if not html:
        return score, reasons

    signals = parse_html(html)

    # --- Hidden iframes ---
    if signals["hidden_iframes"]:
        count = len(signals["hidden_iframes"])
        score += 30
        reasons.append(f"Hidden iframe(s) detected ({count}): {signals['hidden_iframes'][:3]}")

    # --- External scripts ---
    ext_scripts = signals["external_scripts"]
    if len(ext_scripts) > 10:
        score += 10
        reasons.append(f"Large number of external scripts ({len(ext_scripts)})")

    # --- Obfuscated JS ---
    if signals["obfuscated_js"]:
        funcs = list(set(signals["obfuscated_js"]))
        score += 25
        reasons.append(f"Obfuscated JavaScript detected: {', '.join(funcs[:5])}")

    # --- Login form ---
    if signals["login_forms"]:
        score += 20
        reasons.append("Page contains a login/password form (possible phishing)")

    # --- Suspicious keywords ---
    if signals["suspicious_keywords"]:
        kw_score = min(len(signals["suspicious_keywords"]) * 5, 20)
        score += kw_score
        reasons.append(f"Suspicious keywords: {', '.join(signals['suspicious_keywords'][:5])}")

    # --- Redirects ---
    if redirect_count >= 5:
        score += 20
        reasons.append(f"Excessive redirects ({redirect_count})")
    elif redirect_count >= 3:
        score += 10
        reasons.append(f"Multiple redirects ({redirect_count})")

    return score, reasons


def analyze_threat_intelligence(url: str, domain: str) -> tuple[int, list[str]]:
    """
    Query external threat-intelligence services:
      • VirusTotal URL report
      • VirusTotal domain report

    Returns score contribution and explanation list.
    """
    score = 0
    reasons: list[str] = []

    # --- VirusTotal URL ---
    vt_url = vt_url_lookup(url)
    if vt_url:
        if vt_url["malicious"] > 0:
            score += 60
            reasons.append(
                f"VirusTotal: URL flagged as malicious by "
                f"{vt_url['malicious']} engine(s)"
            )
        elif vt_url["suspicious"] > 0:
            score += 30
            reasons.append(
                f"VirusTotal: URL flagged as suspicious by "
                f"{vt_url['suspicious']} engine(s)"
            )

    # --- VirusTotal Domain ---
    vt_dom = vt_domain_lookup(domain)
    if vt_dom:
        if vt_dom["malicious"] > 0:
            score += 40
            reasons.append(
                f"VirusTotal: domain flagged as malicious by "
                f"{vt_dom['malicious']} engine(s)"
            )
        elif vt_dom["suspicious"] > 0:
            score += 20
            reasons.append(
                f"VirusTotal: domain flagged as suspicious by "
                f"{vt_dom['suspicious']} engine(s)"
            )

    return score, reasons


def compute_url_score(
    url: str,
    html_body: str = "",
    redirect_count: int = 0,
    fetch_error: Optional[str] = None,
) -> dict:
    """
    Master scoring function for URL analysis.

    Aggregates results from:
      1. URL structure analysis
      2. Domain intelligence (WHOIS + DNS)
      3. Page content analysis (HTML / JS)
      4. Threat intelligence (VirusTotal)

    Verdict thresholds:
      score <  30  → SAFE
      score 30–60  → SUSPICIOUS
      score >  60  → MALICIOUS

    Returns a dict with score, verdict, and reasons list.
    """
    total_score = 0
    all_reasons: list[str] = []

    parsed = urlparse(url)
    hostname = (parsed.hostname or "").lower()
    extracted = tldextract.extract(url)
    domain = f"{extracted.domain}.{extracted.suffix}".lower()

    # 1. URL structure
    s, r = analyze_url_structure(url)
    total_score += s
    all_reasons.extend(r)

    # 2. Domain intelligence (skip for raw IPs)
    if not is_ip_address(hostname):
        s, r = analyze_domain_intelligence(domain)
        total_score += s
        all_reasons.extend(r)

    # 3. Content analysis
    if html_body:
        s, r = analyze_page_content(html_body, redirect_count)
        total_score += s
        all_reasons.extend(r)
    elif fetch_error:
        all_reasons.append(f"Could not fetch page content: {fetch_error}")

    # 4. Threat intelligence
    s, r = analyze_threat_intelligence(url, domain)
    total_score += s
    all_reasons.extend(r)

    # --- Final verdict ---
    if total_score > 60:
        verdict = "MALICIOUS"
    elif total_score >= 30:
        verdict = "SUSPICIOUS"
    else:
        verdict = "SAFE"

    if not all_reasons:
        all_reasons.append("No indicators triggered")

    return {
        "url": url,
        "domain": domain,
        "score": total_score,
        "verdict": verdict,
        "reasons": all_reasons,
    }





